export const SET_CURRENT_TAB = "SET_CURRENT_TAB";

export const SET_ASSISTANT_MESSAGE_COUNT = "SET_ASSISTANT_MESSAGE_COUNT";

export const SET_ASSISTANT_SHOW = "SET_ASSISTANT_SHOW";

export const SET_ASSISTANT_INPUT = "SET_ASSISTANT_INPUT";

export const SET_CARD_ID = "SET_CARD_ID";
